export {
  AppError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ConflictError,
  InvalidCredentialsError,
  UnauthorizedError,
  ForbiddenError,
  NotRoomCreatorError,
  RoomNotFoundError,
  RoomNotJoinableError,
  RoomFullError,
  AlreadyJoinedError,
  TeamNameTakenError,
  InvalidRoomStateError,
  MinParticipantsRequiredError,
  PlayerPoolEmptyError,
  AdminAccessRequiredError,
  PlayerNotFoundError,
  DuplicateRoomPlayerError,
  AuctionOrderTakenError,
  InvalidAuctionTransitionError,
  AuctionNotFoundError,
  BidRejectedError,
} from './AppError';

